

GET http://localhost:3000/api/user/



###
POST http://localhost:3000/api/user/create
Content-Type: application/json

{
  "name": "Leslie",
  "email": "John@Doe22223.com",
  "password": "password",
  "img": "https://www.google.com"
}