

GET http://localhost:3000/api/user/



###
POST http://localhost:3000/api/user/create

Content-Type: application/json
{
  "name": "John Doe",
  "email": "John@Doe.com",
  "password": "password",
  "img": "https://www.google.com",
  "followers": [],
  "following": [],
  "videos": []
}